<?php
//define('_DB_SERVER_', 'hobivinjpresta16.mysql.db');
//define('_DB_NAME_', 'hobivinjpresta16');
//define('_DB_USER_', 'hobivinjpresta16');
//define('_DB_PASSWD_', 'SuMfzPVP27VU');
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'hobivinjpresta16');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'pre8466_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_COOKIE_KEY_', '');
define('_COOKIE_IV_', 'eAKi4efb');
define('_PS_CREATION_DATE_', '2015-09-20');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.1.1');
define('_RIJNDAEL_KEY_', '7MSxucg0IftBuXthIVf7bUWcEkPknqBJ');
define('_RIJNDAEL_IV_', 'eZB7RvBFNgMnxkl08ToLeg==');
